### ISSUE TITLE
Peer Feedback from Harjyot and Shayne

### ISSUE THREAD

**Issue by shayne-andrews** [UBC-MDS/americas-safest-cities#10]
- multi-select for country and crime type would be nice
- some data missing on line graph
- years dropdown:
    - timeline for years would be very useful
    - what years am I looking at on this graph?
- selected cities on second tab:
    - maybe use a multi-select?
    - or pre-populate defaults with 5 major citis
- map city tooltips to include split of total crimes by type

**Comment by talhaadnan100** [comment]
Appreciate the valuable constructive feedback. We are incorporating it in our app enhancements. Thank you!
