### ISSUE TITLE
Summarized list of proposed enhancements

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/americas-safest-cities#14]
For Milestone 3: 

- [x] Radio button for time intervals x
- [x] Check sizes of plots x
- [x] Check axis labels, font size x
- [x] Change color palettes for TrendChart x
- [x] Knob input/Slider input for years x
- [x] Plotly implementation on TrendChart

For Milestone 4:

Options available to incorporate cool features: 

- [x] See if you can make map full-screen and sidebar translucent and draggable
- [ ] Style the blob
- [x] Radio button for Numbers, Rates
- [x] Specify 2015 on TrendChart

**Comment by makka3** [comment]
No need to style the blob for now, the viz is looking sweet as is. If we decide to keep working on this, we can open another issue for this.
