### ISSUE TITLE
Feedback for Milestone 3

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/americas-safest-cities#16]
The app is looking good and well organized. 

There is a minor issue with the type-in input for year - entering anything with 19.. doesnt work. And it seems like the issue of selecting multiple years should be easily fixable - change it to a radio button format, maybe?

Other than that, rest of the app works fine and you're code is very well laid out and documented.

**Comment by makka3** [comment]
Hey Sahir,

Thanks for your feedback and helpful input throughout this project. For Milestone 4, we have improved on our design in the following ways:

- Map scaling
- Adding city rankings
- Number/rate toggling for the map
- Draggable panel in the map
- Some bug fixes
- Addition of national averages on line graph tab

Unfortunately, we were not able to address the issues with the knob in time for this submission. This can be addressed for the future by either by using a different widget (such as a number line) or altering the parameters within the 'KnobInput' call such that it can take in any number. As for the issue of selecting multiple years, we have chosen to stick with the single year format as we feel that it conveys more information with regards to the use case than having multiple years be selected.

Thanks again for the feedback.
