### ISSUE TITLE
Milestone 1: Feedback

### ISSUE THREAD

**Issue by ghost** [UBC-MDS/americas-safest-cities#4]
Great write-up -  it was succinct and informative.

There was really no need to list all the variables that you were including in the table. I question your logic of disregarding stats where all 12 months aren't reported. What if in cold cities crime rates drop during winters and so no crimes occur in January? This would mean that all of those stats for that particular year/city would be effectively left out. Maybe think a bit more about this using by exploring the data or thinking about hypothetical situations.

As a plus, I really like the logic regarding the usage of 2015 (or most recent date in the data) as the baseline to compare historical trends and time spans. Good thinking on that!

**Comment by talhaadnan100** [comment]
Appreciate the valuable input. We are incorporating some of the changes you have suggested it in our app enhancements. Thank you!
