### ISSUE TITLE
Milestone 2 Peer Feedback

### ISSUE THREAD

**Issue by heathervant** [UBC-MDS/americas-safest-cities#9]
Great app! Very clear on what the data is conveying. very nice layout of first exploratory map tab and then the second comparison.  You may want to consider the following: 
- make font size on plots bigger. 

- decide on whether you want the years to be non-selectable and just display 40 years (the full data set) and then use plotly to interact with the chart by zooming in on specific cities 

- consider changing title from America's safest cities to "America's most dangerous cities" or "crime rates by US city". 
- color by type of crime on the map somehow.. either pie chart or different colored circles for each. 
-  consider having a chart that ranks all of the cities

**Comment by talhaadnan100** [comment]
Appreciate the valuable constructive feedback. We are incorporating it in our app enhancements. Thank you!
